apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: all-nginx-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80