apiVersion: v1
kind: Pod
metadata:
  name: redis-pod2
  namespace: default
  labels:
    app.kubernetes.io/name: all-nginx-label
spec:
  containers:
    - name: redis-app
      image: redis:latest
      ports:
        - containerPort: 6379
