# kubectl create secret generic my-db-secret --from-literal=user=gopal --from-literal=password=admin123
#below we can see data is base64:q!
apiVersion: v1
data:
  password: YWRtaW4xMjM=
  user: Z29wYWw=
kind: Secret
metadata:
  name: my-db-secret
  namespace: develop-staging
type: Opaque