apiVersion: v1
kind: Pod
metadata: 
  name: nginx-webpod-with-secret
spec:
  containers:
  - name: nginxapp
    image: nginx:1.14.2
    ports:
      - name: http
        containerPort: 80
    env:
    - name: Username
      valueFrom:
        secretKeyRef:
          name: my-db-secret
          key: user
    - name: Password
      valueFrom:
        secretKeyRef:
          name: my-db-secret
          key: password

