# kubectl create secret docker-registry my-docker-secret --docker-email=gopal@zyz.com --docker-username=gjee --docker-password=pass1234 --docker-server=my-registery.example:5000
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJteS1yZWdpc3RlcnkuZXhhbXBsZTo1MDAwIjp7InVzZXJuYW1lIjoiZ2plZSIsInBhc3N3b3JkIjoicGFzczEyMzQiLCJlbWFpbCI6ImdvcGFsQHp5ei5jb20iLCJhdXRoIjoiWjJwbFpUcHdZWE56TVRJek5BPT0ifX19
kind: Secret
metadata:
  name: my-docker-secret
  namespace: develop-staging
type: kubernetes.io/dockerconfigjson
