apiVersion: v1
kind: Pod
metadata: 
  name: nginx-webpod-with-docker-secret
spec:
  containers:
  - name: nginxapp
    image: nginx:latest
    ports:
      - name: http
        containerPort: 80
    envFrom:
    - secretRef:
      name: my-docker-secret
